
SCREEN_SIZE = SCREEN_WIDTH, SCREEN_HEIGHT = 700,700
PLAYER_SIZE = 35

PLAYER_START_POSITIONS = [(PLAYER_SIZE/2,PLAYER_SIZE/2), (SCREEN_WIDTH-PLAYER_SIZE/2, PLAYER_SIZE/2), \
                          (PLAYER_SIZE/2, SCREEN_HEIGHT-PLAYER_SIZE/2), (SCREEN_WIDTH-PLAYER_SIZE/2, SCREEN_HEIGHT-PLAYER_SIZE/2)]

#----- Movable gameobject constants-----#
STEPSIZE = 1.5
MINMOVEFREQ = 0.15